:lib: pass:quotes[_library_]
:libs: pass:quotes[_libraries_]
:j: Java
:fs: functies
:f: functie
:m: method
:icons: font
:source-highlighter: rouge

= Exceptions
//Author Mark Nuyts
//v0.1
:toc: left
:toclevels: 4

Wanneer we Java _code_ uitvoeren kunnen zich verschillende fouten, uitzonderingen of gebeurtenissen voordoen #die de normale werking van een programma onderbreken#: fouten gemaakt door de programmeur, verkeerde _input_ of andere **onvoorziene zaken**.
Over het algemeen is een _exception_ iets wat we #zoveel mogelijk willen vermijden# in een programma, maar waar we in veel gevallen toch rekening mee kunnen en moeten houden.
Een voorbeeld is het inlezen van een bestand: dit loopt normaal gezien goed, maar wat als het bestand corrupt is? Of niet gevonden kan worden? In die gevallen spreken we van een _exception_.

Wanneer er zich een _exception voordoet zal het Java programma normaal gezien stoppen met uitvoeren en een _error_ boodschap tonen. De term die hiervoor wordt gebruikt is: 

====
Java will *throw* an exception (throw an error).
====

Er zijn 2 grote groepen van _Exceptions_, namelijk:

* *Checked* exceptions -> Deze fouten zijn verplicht op te vangen (de compiler controleert dit).
* *Unchecked* exceptions -> De programmeur wordt niet verplicht met deze fouten rekening te houden.

== Java try and catch

Dankzij het **try/catch _statement_** kunnen we als programmeur omgaan met _exceptions_.
Het __try statement__ laat het toe bepaalde code uit te voeren en een mogelijke fout op te vangen in het bijhorende __catch statement__.

De _code_ in het __catch statement__ of __catch block__ wordt enkel uitgevoerd indien er zich een fout voordeed. Anders niet.

[source,java]
----
try {
  //  Block of code to try <1>
} catch(Exception e) {
  //  Block of code to handle errors <2>
}
----
<1> De _code_ die men wil uitvoeren.
<2> De _code_ die wordt uitgevoerd indien er zich een fout voordeed in de _code_ van het __try block__ (1).

=== Finally

Naast de try/catch kunnen we ook gebruik maken van de *optionele* _finally_. Dit is niet verplicht.
De finally wordt altijd uitgevoerd na het doorlopen van de _try_ en de _catch_.
Dus zowel indien er zich wel of geen fout heeft voorgedaan.

[source,java]
----
try {
  //  Block of code to try
} catch(Exception e) {
  //  Block of code to handle errors
} finally { <1>
  // Always executed 
}
----
<1> De _finally_ wordt steeds uitgevoerd na de _try_ of de _catch_.


== Checked exceptions

Deze _exceptions_ zijn uitzonderingen die binnen de verwachtingen liggen en waarvan van de programmeur verwacht wordt dat hij er #op voorhand rekening mee houdt#.

Bijvoorbeeld bij het inlezen van een bestand (_file_), geeft de _compiler_ onmiddelijk al aan dat er rekening moet worden gehouden met een _exception_ (het bestand kan mogelijk niet gevonden worden, of het bestand kan corrupt zijn):

[source,java]
----
File bestand = new File("C:\temp\tekst.txt");
Scanner s = new Scanner(bestand);
----

image::scannerexception.png[]

De _exception_ die heer verwacht wordt, is de FileNotFoundException.
Dit is een subklasse van IOException, wat op zijn beurt een subklasse is van Exception.

Om hiermee rekeing te houden in de _code_, verplicht de _compiler_ ons om een _try/catch_ toe te voegen:

[source,java]
----
		File bestand = new File("C:\\temp\\tekst.txt");
		try {
			Scanner s = new Scanner(bestand);
		} catch (FileNotFoundException e) { <1>
			System.out.println("Spijtig, maar er iets iets mis met het bestand."); <2>
			e.printStackTrace(); <3>
		}
----
<1> De FileNotFoundException die we opvangen indien het zich voordoet.
<2> Indien de fout zich voordoet, kunnen we een actie ondernemen (in dit geval een boodschap naar de console printen).
<3> De _stacktrace_ geeft in detail weer hoe de fout zich heeft voorgedaan.

Een voorbeeld van de _stacktrace_ :

----
java.io.FileNotFoundException: C:\temp\tekst.txt (Het systeem kan het opgegeven bestand niet vinden) <1>
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.util.Scanner.<init>(Scanner.java:639)
	at Scannervoorbeeld.method1(Scannervoorbeeld.java:19)
	at Scannervoorbeeld.main(Scannervoorbeeld.java:13)
----
<1> In een _stacktrace_ wordt meestal duidelijk aangegeven welke fout zich net voordeed.


== Unchecked exceptions

Deze _exceptions_ zijn subklassen van #_runtime_ _exceptions_#. Deze kunnen zich voordoen bij het draaien van het programma, maar hier verwacht de _compiler_ niet dat je er op voorhand rekening mee houdt.

Een veel voorkomend voorbeeld van een _runtime exception_ is de _NullPointerException_.
Deze doet zich voor wanneer de waarde van een niet-ge√Ønitialiseerde variabele wordt opgehaald:

[source,java]
----
	public void method1() {
		method2(null);
	}
	
	public void method2(Integer a) {
		a.intValue(); <1>
	}
----
<1> Hier zal zich een nullpointer voordoen, want de Integer a is _null_.

De _stacktrace_:

----
Exception in thread "main" java.lang.NullPointerException
	at Scannervoorbeeld.method2(Scannervoorbeeld.java:21)
	at Scannervoorbeeld.method1(Scannervoorbeeld.java:17)
	at Scannervoorbeeld.main(Scannervoorbeeld.java:13)
----


== Throws / throw

=== Throw

Met het _throw_ _keyword_ geven we aan dat we zelf een _exception_ aanmaken of lanceren:

[source,java]
----
throw new Exception("De invoer is niet correct."); <1>
----
<1> We maken een nieuwe *instantie* aan van een exception en _throwen_ deze.

=== Throws

Wanneer we bovenstaande _code_ gebruiken in een _method_. 
*Moet* de method aangeven dat er een _exception_ _gethrowed_ wordt:

[source,java]
----
public void executeCode() throws Exception { <1>
  throw new Exception("De invoer is niet correct."); <2>
}
----
<1> Met *throws* geven we aan dat de _method_ *mogelijk* een _exception_ gaat _throwen_.
<2> Een nieuwe instantie van een _exception_ wordt _gethrowed_.

Indien je gebruik maakt van bovenstaande _method_, verplicht de compiler je om een __try/catch block__ te gebruiken om de mogelijke _exception_ op te vangen.

[IMPORTANT]
====
Dit is **niet het geval voor subklassen van __runtime exceptions__**: dit zijn immers __unchecked exceptions__.
====

== Custom exception

We kunnen zelf een eigen subklasse van _exception_ maken:

[source,java]
----
public class MijnException extends Exception{
	public MijnException(String message) {
        super(message);
    }
}
----

Deze kan vervolgens in je _code_ met een _throw_ en een _throws_ gebruikt worden:

[source,java]
----
public void method1() throws MijnException {
		throw new MijnException("fout");
	}
----
